baseURL = "https://gunnsoo.com/"
languageCode = "ja"
title = "gunnsoo's blog"
theme = "beautifulhugo"
hasCJKLanguage = true
googleAnalytics = 'G-9ZH1Z1NSCC'

[Author]
  name = "gunnsoo"
  github = "gunnsoo"
  twitter = "gnnsoo"
  linkedin = "kazuki-sugai-482875192"
  atcoder = "pybot114514"
  qiita = "gunnsoo"

[Params]
  favicon = "img/favicon.ico"
  logo = "img/logo.png"
  readingTime = true
  wordCount = true
  socialShare = true
  showRelatedPosts = true
  amazonJpAffiliate = "gunnsoo-22"
  customCSS = ["/css/amazon.css"]

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "TOP"
  url = "/"
  weight = 1

[[menu.main]]
  name = "TAGS"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "ABOUT"
  url = "about"
  weight = 3