baseURL = "https://blog.gunnsoo.com/"
languageCode = "ja"
title = "gunnsoo's blog"
theme = "beautifulhugo"

[Author]
  name = "Kazuki Sugai"
  github = "gunnsoo"
  twitter = "gnnsoo"
  linkedin = "kazuki-sugai-482875192"

[[menu.main]]
    name = "TOP"
    url = ""
    weight = 1

[[menu.main]]
    name = "ABOUT"
    url = "about/"
    weight = 2